{
 "title": "IssuerVerifier AcaPy Logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aggregation_period", "label": "Aggregation Period", "query": "1h, 12h, 1d, 2d, 7d, 30d" },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Errors Logged by AcaPy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of undelivered Webhook Events  [Last $aggregation_period]",
   "type": "stat",
   "description": "This counter only counts those events that could not be delivered even after retrying it multiple times.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n  {compose_service=\"issuer-verifier-acapy\"} |= \"aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued\"\n[$aggregation_period])"
    }
   ]
  },
  {
   "title": "Number of Failed Delivery Attempts [$rate_interval]",
   "type": "state-timeline",
   "description": "Since all failed deliveries will be retired, the event might still have been delivered successfully.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum (count_over_time(\n  {compose_service=\"issuer-verifier-acapy\"} |= \"aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to\" | pattern \"<_>aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: <client>/topic/<_>; Error:<_>\"\n[$rate_interval])) by (client)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Number of Tails File uploads that failed [Last $aggregation_period]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n  {compose_service=\"issuer-verifier-acapy\"} |= \"aries_cloudagent.revocation.error.RevocationError: Tails file for rev reg\" |= \"failed to upload\"\n[$aggregation_period])",
     "legendFormat": "{{httpMethod}} {{uri}} [{{httpCode}}]: {{message}} "
    }
   ]
  },
  {
   "title": "Number of Tails File uploads that failed [$rate_interval]",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum (count_over_time(\n  {compose_service=\"issuer-verifier-acapy\"} |= \"aries_cloudagent.revocation.error.RevocationError: Tails file for rev reg\" |= \"failed to upload\" | pattern \"aries_cloudagent.revocation.error.RevocationError: Tails file for rev reg <revReg> failed to upload: Exceeded maximum put attempts\"\n[$rate_interval])) by (revReg)",
     "legendFormat": "RevReg: {{revReg}}"
    }
   ]
  }
 ]
}