{
 "title": "Summary",
 "time": { "from": "2022-02-18T16:20:48.926Z", "to": "2022-02-19T00:19:57.816Z" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "instance", "label": "Database Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\".*\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Test Result Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Iterations Finished (per Minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time(\n  {app=\"aries-load-generator\"}\n    |= \"Finished\"\n    |= \"of\"\n    |= \"iterations\"\n[1m])"
    }
   ]
  },
  {
   "title": "Connection Protocol Transition Times  (per Minute in Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=ACTIVE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=INVITATION\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "E2E - INVITATION to ACTIVE"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=REQUEST\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=INVITATION\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "INVITATION to REQUEST"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=RESPONSE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=REQUEST\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "REQUEST to RESPONSE"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=ACTIVE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=RESPONSE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "RESPONSE to ACTIVE"
    }
   ]
  },
  {
   "title": "Credential Issuance Protocol Transition Times  (per Minute in Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ACKED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=OFFER_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "E2E - OFFER_SENT to CREDENTIAL_ACKED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=REQUEST_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=OFFER_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "OFFER_SENT to REQUEST_RECEIVED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ISSUED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=REQUEST_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "REQUEST_RECEIVED to CREDENTIAL_ISSUED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ACKED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ISSUED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "CREDENTIAL_ISSUED to CREDENTIAL_ACKED"
    }
   ]
  },
  {
   "title": "Proof Request Protocol Transition Times  (per minute in Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=VERIFIED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=REQUEST_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId)\n)",
     "legendFormat": "E2E - REQUEST_SENT to VERIFIED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=PRESENTATION_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=REQUEST_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId)\n)",
     "legendFormat": "REQUEST_SENT to PRESENTATION_RECEIVED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=VERIFIED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=PRESENTATION_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId)\n)",
     "legendFormat": "PRESENTATION_RECEIVED to VERIFIED"
    }
   ]
  },
  {
   "title": "Errors Raised by AcaPy - Admin API (Issuer/Verifier and Holder)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Total Number of HTTP Request to AcaPy without HTTP Code 200",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n  {app=\"aries-load-generator\"}\n    |= \"type=http_request\"\n    != \"httpCode=200\"\n[10d])"
    }
   ]
  },
  {
   "title": "Number of known AcaPy HTTP Errors (per Minute)",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count_over_time(\n {app=\"aries-load-generator\"}\n  |= \"type=http_request\"\n  |= \"request=POST/connections/create-invitation httpCode=400\"\n[1m])",
     "legendFormat": "POST/connections/create-invitation [HTTP 400]"
    },
    {
     "expr": "count_over_time(\n {app=\"aries-load-generator\"}\n    |= \"type=http_request\"\n    |= \"POST/connections/receive-invitation\"\n    != \"httpCode=200\"\n[1m])",
     "legendFormat": "POST/connections/receive-invitation"
    },
    {
     "expr": "count_over_time(\n {app=\"aries-load-generator\"}\n  |= \"type=http_request\"\n  |= \"request=POST/issue-credential/send httpCode=400\"\n[1m])",
     "legendFormat": "POST/issue-credential/send [HTTP 400]"
    }
   ]
  },
  {
   "title": "New AcaPy HTTP Errors",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": " {app=\"aries-load-generator\"}\n    |= \"type=http_request\"\n    != \"httpCode=200\"\n    != \"request=POST/connections/create-invitation httpCode=400\"\n    != \"request=POST/issue-credential/send httpCode=400\"\n    != \"POST/connections/receive-invitation\""
    }
   ]
  },
  {
   "title": "Errors Raises by AcaPy - Webhooks (Issuer/Verifier)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Total Number of Errors Reported by AcaPy Webhooks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n   {app=\"aries-load-generator\"}\n    |= \"type=error\"\n    |= \"AcaPyPublisher\"\n[10d])"
    }
   ]
  },
  {
   "title": "Number of known Errors (per Minute)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "count_over_time(\n {app=\"aries-load-generator\"}\n    |= \"type=error\"\n    |= \"AcaPyPublisher.handleCredential: Revocation registry metadata not found.\"\n[1m])",
     "legendFormat": "AcaPyPublisher.handleCredential: Revocation registry metadata not found."
    },
    {
     "expr": "count_over_time(\n {app=\"aries-load-generator\"}\n    |= \"type=error\"\n    |= \"AcaPyPublisher.handleCredential: Record not found.\"\n[1m])",
     "legendFormat": "AcaPyPublisher.handleCredential: Record not found."
    }
   ]
  },
  {
   "title": "New Errors Reported by AcaPy Webhooks",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": " {app=\"aries-load-generator\"}\n    |= \"type=error\"\n    |= \"AcaPyPublisher\"\n    != \"AcaPyPublisher.handleCredential: Revocation registry metadata not found.\"\n    != \"AcaPyPublisher.handleCredential: Record not found.\""
    }
   ]
  },
  { "title": "Issuer/Verifier Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{instance=\"$instance\", datname=\"$db\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Lock Tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{instance=\"$instance\", datname=\"$db\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Docker Container Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\".*\",name=~\"$container\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\".*\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}