{
 "title": "Full Process",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of Iterations started per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time(\n  {app=\"aries-load-generator\"}\n    |= \"Started\"\n    |= \"of\"\n    |= \"iteration\"\n[1m])"
    }
   ]
  },
  { "title": "Aries Event Logger - General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Number of Connection Invitations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=connectionRecord\"\n  |= \"state=INVITATION\" [10d])"
    }
   ]
  },
  {
   "title": "Total Number Credential Offers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=credentialRecord\"\n  |= \"state=OFFER_SENT\" [10d])"
    }
   ]
  },
  {
   "title": "Number of Pending Proof Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=presentationRecord\"\n  |= \"state=REQUEST_SENT\" [10d]) -\n  \ncount_over_time({app=\"aries-load-generator\"}\n  |= \"type=presentationRecord\"\n  |= \"state=VERIFIED\" [10d])"
    }
   ]
  },
  {
   "title": "Number of Pending Connection Invitations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=connectionRecord\"\n  |= \"state=INVITATION\" [10d]) -\n  \ncount_over_time({app=\"aries-load-generator\"}\n  |= \"type=connectionRecord\"\n  |= \"state=ACTIVE\" [10d])"
    }
   ]
  },
  {
   "title": "Number of Pending Credential Offers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=credentialRecord\"\n  |= \"state=OFFER_SENT\" [10d]) -\n  \ncount_over_time({app=\"aries-load-generator\"}\n  |= \"type=credentialRecord\"\n  |= \"state=CREDENTIAL_ACKED\" [10d])"
    }
   ]
  },
  {
   "title": "Total Number of Proof Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=presentationRecord\"\n  |= \"state=REQUEST_SENT\" [10d])"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=connectionRecord\"\n  |= \"state=INVITATION\" [10d])",
     "legendFormat": "Invited"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=connectionRecord\"\n  |= \"state=REQUEST\" [10d])",
     "legendFormat": "Requested"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=connectionRecord\"\n  |= \"state=RESPONSE\" [10d])",
     "legendFormat": "Responded"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=connectionRecord\"\n  |= \"state=ACTIVE\" [10d])",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Credential Issuance Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=credentialRecord\"\n  |= \"state=OFFER_SENT\" [10d])",
     "legendFormat": "Offers Sent"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=credentialRecord\"\n  |= \"state=REQUEST_RECEIVED\" [10d])",
     "legendFormat": "Request Received"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=credentialRecord\"\n  |= \"state=CREDENTIAL_ISSUED\" [10d])",
     "legendFormat": "Issued"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=credentialRecord\"\n  |= \"state=CREDENTIAL_ACKED\" [10d])",
     "legendFormat": "Issuance Acknowledged"
    }
   ]
  },
  {
   "title": "Proof Request Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=presentationRecord\"\n  |= \"state=REQUEST_SENT\" [10d])",
     "legendFormat": "Sent"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=presentationRecord\"\n  |= \"state=PRESENTATION_RECEIVED\" [10d])",
     "legendFormat": "Received Presentation"
    },
    {
     "expr": "count_over_time({app=\"aries-load-generator\"}\n  |= \"type=presentationRecord\"\n  |= \"state=VERIFIED\" [10d])",
     "legendFormat": "Verified"
    }
   ]
  },
  {
   "title": "Connection Activation Rate (in Minutes)",
   "type": "timeseries",
   "description": "Average Number of Connections that are being activated per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(\n  {app=\"aries-load-generator\"}\n    |= \"type=connectionRecord\"\n    |= \"state=ACTIVE\"\n[1m])",
     "legendFormat": "Connection Activations per Second"
    }
   ]
  },
  {
   "title": " Credential Issuance Rate (in Minutes)",
   "type": "timeseries",
   "description": "Average Number of Credentials issued per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "rate(\n  {app=\"aries-load-generator\"}\n    |= \"type=credentialRecord\"\n    |= \"state=CREDENTIAL_ACKED\"\n[1m])",
     "legendFormat": "Credentials Issued per Second"
    }
   ]
  },
  {
   "title": " Proof Request Verification Rate (in Minutes)",
   "type": "timeseries",
   "description": "Average Number of Proof Requests verified per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "rate(\n  {app=\"aries-load-generator\"}\n    |= \"type=presentationRecord\"\n    |= \"state=VERIFIED\"\n[1m])",
     "legendFormat": "Proof Requests verified per Second"
    }
   ]
  },
  {
   "title": "Aries Event Logger - State Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Connection Protocol Transition Times  (in Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=ACTIVE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=INVITATION\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "E2E - INVITATION to ACTIVE"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=REQUEST\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=INVITATION\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "INVITATION to REQUEST"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=RESPONSE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=REQUEST\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "REQUEST to RESPONSE"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=ACTIVE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=connectionRecord\"\n      |= \"state=RESPONSE\"\n      | logfmt \n      | unwrap time\n  [1m]) by (connectionId)\n)",
     "legendFormat": "RESPONSE to ACTIVE"
    }
   ]
  },
  {
   "title": "Credential Issuance Protocol Transition Times  (in Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ACKED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=OFFER_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "E2E - OFFER_SENT to CREDENTIAL_ACKED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=REQUEST_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=OFFER_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "OFFER_SENT to REQUEST_RECEIVED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ISSUED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=REQUEST_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "REQUEST_RECEIVED to CREDENTIAL_ISSUED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ACKED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=credentialRecord\"\n      |= \"state=CREDENTIAL_ISSUED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (credentialExchangeId)\n)",
     "legendFormat": "CREDENTIAL_ISSUED to CREDENTIAL_ACKED"
    }
   ]
  },
  {
   "title": "Proof Request Protocol Transition Times  (in Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=VERIFIED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=REQUEST_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId)\n)",
     "legendFormat": "E2E - REQUEST_SENT to VERIFIED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=PRESENTATION_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=REQUEST_SENT\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId)\n)",
     "legendFormat": "REQUEST_SENT to PRESENTATION_RECEIVED"
    },
    {
     "expr": "avg (\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=VERIFIED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId) -\n\n  max_over_time (\n    {app=\"aries-load-generator\"}\n      |= \"type=presentationRecord\"\n      |= \"state=PRESENTATION_RECEIVED\"\n      | logfmt \n      | unwrap time\n  [1m]) by (presentationExchangeId)\n)",
     "legendFormat": "PRESENTATION_RECEIVED to VERIFIED"
    }
   ]
  },
  { "title": "HTTP Logger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Number of HTTP Request without HTTP Code 200",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n  {app=\"aries-load-generator\"}\n    |= \"type=http_request\"\n    != \"httpCode=200\"\n[10d])"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "count_over_time(\n  {app=\"aries-load-generator\"}\n    |= \"type=http_request\"\n    |= \"httpCode=200\"\n[10d])",
     "legendFormat": "HTTP Code 200"
    },
    {
     "expr": "count_over_time(\n  {app=\"aries-load-generator\"}\n    |= \"type=http_request\"\n    != \"httpCode=200\"\n[10d])",
     "legendFormat": "HTTP Code != 200"
    }
   ]
  },
  {
   "title": "HTTP Response Times (in Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "avg_over_time (\n  {app=\"aries-load-generator\"}\n    |= \"type=http_request\"\n    |= \"httpCode=200\"\n    != \"request=POST/schemas\"\n    != \"request=POST/credential-definitions\"\n    | logfmt\n    | unwrap durationInMs\n[1m]) by (request)"
    }
   ]
  },
  { "title": "Wallet Database Logger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Wallet Database Size (in MB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"aries-load-generator\",level=\"INFO\"} |= \"type=database_size\" | logfmt | unwrap sizeInBytes [10m])) / 1024 / 1024"
    }
   ]
  }
 ]
}